# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/gpio_pins3/user_const.xdc

# Block Designs: bd/cont_microblaze/cont_microblaze.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze || ORIG_REF_NAME==cont_microblaze} -quiet] -quiet

# IP: bd/cont_microblaze/ip/cont_microblaze_axi_hwicap_0_0/cont_microblaze_axi_hwicap_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze_axi_hwicap_0_0 || ORIG_REF_NAME==cont_microblaze_axi_hwicap_0_0} -quiet] -quiet

# IP: bd/cont_microblaze/ip/cont_microblaze_axi_quad_spi_0_0/cont_microblaze_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze_axi_quad_spi_0_0 || ORIG_REF_NAME==cont_microblaze_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/cont_microblaze/ip/cont_microblaze_axi_slave_wishbone_classic_master_0_0/cont_microblaze_axi_slave_wishbone_classic_master_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze_axi_slave_wishbone_classic_master_0_0 || ORIG_REF_NAME==cont_microblaze_axi_slave_wishbone_classic_master_0_0} -quiet] -quiet

# IP: bd/cont_microblaze/ip/cont_microblaze_axi_timebase_wdt_0_0/cont_microblaze_axi_timebase_wdt_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze_axi_timebase_wdt_0_0 || ORIG_REF_NAME==cont_microblaze_axi_timebase_wdt_0_0} -quiet] -quiet

# IP: bd/cont_microblaze/ip/cont_microblaze_axi_timer_0_0/cont_microblaze_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze_axi_timer_0_0 || ORIG_REF_NAME==cont_microblaze_axi_timer_0_0} -quiet] -quiet

# IP: bd/cont_microblaze/ip/cont_microblaze_axi_uartlite_0_0/cont_microblaze_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze_axi_uartlite_0_0 || ORIG_REF_NAME==cont_microblaze_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/cont_microblaze/ip/cont_microblaze_mdm_1_0/cont_microblaze_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze_mdm_1_0 || ORIG_REF_NAME==cont_microblaze_mdm_1_0} -quiet] -quiet

# IP: bd/cont_microblaze/ip/cont_microblaze_microblaze_0_0/cont_microblaze_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze_microblaze_0_0 || ORIG_REF_NAME==cont_microblaze_microblaze_0_0} -quiet] -quiet

# IP: bd/cont_microblaze/ip/cont_microblaze_microblaze_0_axi_intc_0/cont_microblaze_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze_microblaze_0_axi_intc_0 || ORIG_REF_NAME==cont_microblaze_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/cont_microblaze/ip/cont_microblaze_xbar_0/cont_microblaze_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze_xbar_0 || ORIG_REF_NAME==cont_microblaze_xbar_0} -quiet] -quiet

# IP: bd/cont_microblaze/ip/cont_microblaze_microblaze_0_axi_periph_0/cont_microblaze_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze_microblaze_0_axi_periph_0 || ORIG_REF_NAME==cont_microblaze_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/cont_microblaze/ip/cont_microblaze_dlmb_bram_if_cntlr_0/cont_microblaze_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==cont_microblaze_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/cont_microblaze/ip/cont_microblaze_dlmb_v10_0/cont_microblaze_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze_dlmb_v10_0 || ORIG_REF_NAME==cont_microblaze_dlmb_v10_0} -quiet] -quiet

# IP: bd/cont_microblaze/ip/cont_microblaze_ilmb_bram_if_cntlr_0/cont_microblaze_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==cont_microblaze_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/cont_microblaze/ip/cont_microblaze_ilmb_v10_0/cont_microblaze_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze_ilmb_v10_0 || ORIG_REF_NAME==cont_microblaze_ilmb_v10_0} -quiet] -quiet

# IP: bd/cont_microblaze/ip/cont_microblaze_lmb_bram_0/cont_microblaze_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze_lmb_bram_0 || ORIG_REF_NAME==cont_microblaze_lmb_bram_0} -quiet] -quiet

# IP: bd/cont_microblaze/ip/cont_microblaze_rst_Clk_100M_0/cont_microblaze_rst_Clk_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze_rst_Clk_100M_0 || ORIG_REF_NAME==cont_microblaze_rst_Clk_100M_0} -quiet] -quiet

# IP: bd/cont_microblaze/ip/cont_microblaze_xlconcat_0_0/cont_microblaze_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze_xlconcat_0_0 || ORIG_REF_NAME==cont_microblaze_xlconcat_0_0} -quiet] -quiet

# IP: bd/cont_microblaze/ip/cont_microblaze_auto_pc_0/cont_microblaze_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cont_microblaze_auto_pc_0 || ORIG_REF_NAME==cont_microblaze_auto_pc_0} -quiet] -quiet

# XDC: bd/cont_microblaze/cont_microblaze_ooc.xdc
