# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xcku115-flvf1924-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.cache/wt [current_project]
set_property parent.project_path /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths /home/kplant/software/caltech-lwa/mlib_devel/jasper_library/hdl_sources/axi_wb_bridge/ip_repo [current_project]
update_ip_catalog
set_property ip_output_repo /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/imports/onegbe/arp_cache_init.coe
read_verilog -library xil_defaultlib {
  /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/imports/onegbe/CRC_chk.v
  /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/imports/onegbe/CRC_gen.v
  /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/imports/onegbe/gbe_cpu_attach_wb.v
  /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/imports/onegbe/gbe_rx.v
  /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/imports/onegbe/gbe_tx.v
  /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/imports/onegbe/gbe_udp.v
  /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/imports/onegbe/gig_eth_mac.v
  /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/imports/onegbe/gig_eth_mac_rx.v
  /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/imports/onegbe/gig_eth_mac_tx.v
  /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/imports/infrastructure/snap2_v2_infrastructure.v
  /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/imports/sys_block/sys_block.v
  /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/imports/wbs_arbiter/timeout.v
  /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/imports/wb_register_ppc2simulink/wb_register_ppc2simulink.v
  /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/imports/wb_register_simulink2ppc/wb_register_simulink2ppc.v
  /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/imports/wbs_arbiter/wbs_arbiter.v
  /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/imports/gpio_pins3/top.v
}
read_vhdl -library xil_defaultlib {
  /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/imports/sysgen/conv_pkg.vhd
  /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/imports/gpio_ext2simulink/gpio_ext2simulink.vhd
  /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/imports/sysgen/gpio_pins3_entity_declarations.vhd
  /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/imports/sysgen/xlclockdriver_rd.vhd
  /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/imports/sysgen/gpio_pins3.vhd
  /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/imports/gpio_simulink2ext/gpio_simulink2ext.vhd
  /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/imports/sysgen/single_reg_w_init.vhd
  /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/imports/sysgen/srl33e.vhd
  /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/imports/sysgen/synth_reg.vhd
  /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/imports/sysgen/synth_reg_reg.vhd
  /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/imports/sysgen/synth_reg_w_init.vhd
}
add_files /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/cont_microblaze.bd
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_axi_hwicap_0_0/cont_microblaze_axi_hwicap_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_axi_hwicap_0_0/cont_microblaze_axi_hwicap_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_axi_hwicap_0_0/cont_microblaze_axi_hwicap_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_axi_quad_spi_0_0/cont_microblaze_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_axi_quad_spi_0_0/cont_microblaze_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_axi_quad_spi_0_0/cont_microblaze_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_axi_quad_spi_0_0/cont_microblaze_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_axi_timebase_wdt_0_0/cont_microblaze_axi_timebase_wdt_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_axi_timebase_wdt_0_0/cont_microblaze_axi_timebase_wdt_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_axi_timer_0_0/cont_microblaze_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_axi_timer_0_0/cont_microblaze_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_axi_uartlite_0_0/cont_microblaze_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_axi_uartlite_0_0/cont_microblaze_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_axi_uartlite_0_0/cont_microblaze_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_mdm_1_0/cont_microblaze_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_mdm_1_0/cont_microblaze_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_microblaze_0_0/cont_microblaze_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_microblaze_0_0/cont_microblaze_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_microblaze_0_0/cont_microblaze_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_microblaze_0_axi_intc_0/cont_microblaze_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_microblaze_0_axi_intc_0/cont_microblaze_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_microblaze_0_axi_intc_0/cont_microblaze_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_xbar_0/cont_microblaze_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_dlmb_bram_if_cntlr_0/cont_microblaze_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_dlmb_v10_0/cont_microblaze_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_dlmb_v10_0/cont_microblaze_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_ilmb_bram_if_cntlr_0/cont_microblaze_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_ilmb_v10_0/cont_microblaze_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_ilmb_v10_0/cont_microblaze_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_lmb_bram_0/cont_microblaze_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_rst_Clk_100M_0/cont_microblaze_rst_Clk_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_rst_Clk_100M_0/cont_microblaze_rst_Clk_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_rst_Clk_100M_0/cont_microblaze_rst_Clk_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_auto_pc_0/cont_microblaze_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/cont_microblaze_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_microblaze_0_0/data/mb_bootloop_le.elf]

read_ip -quiet /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gbe_tx_packet_fifo/gbe_tx_packet_fifo.xci
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gbe_tx_packet_fifo/gbe_tx_packet_fifo.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gbe_tx_packet_fifo/gbe_tx_packet_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gbe_tx_packet_fifo/gbe_tx_packet_fifo_ooc.xdc]

read_ip -quiet /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gpio_pins3_c_addsub_v12_0_i0/gpio_pins3_c_addsub_v12_0_i0.xci
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gpio_pins3_c_addsub_v12_0_i0/gpio_pins3_c_addsub_v12_0_i0_ooc.xdc]

read_ip -quiet /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gbe_rx_ctrl_fifo/gbe_rx_ctrl_fifo.xci
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gbe_rx_ctrl_fifo/gbe_rx_ctrl_fifo.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gbe_rx_ctrl_fifo/gbe_rx_ctrl_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gbe_rx_ctrl_fifo/gbe_rx_ctrl_fifo_ooc.xdc]

read_ip -quiet /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gbe_rx_packet_fifo/gbe_rx_packet_fifo.xci
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gbe_rx_packet_fifo/gbe_rx_packet_fifo.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gbe_rx_packet_fifo/gbe_rx_packet_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gbe_rx_packet_fifo/gbe_rx_packet_fifo_ooc.xdc]

read_ip -quiet /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gbe_ctrl_fifo/gbe_ctrl_fifo.xci
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gbe_ctrl_fifo/gbe_ctrl_fifo.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gbe_ctrl_fifo/gbe_ctrl_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gbe_ctrl_fifo/gbe_ctrl_fifo_ooc.xdc]

read_ip -quiet /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_sgmii_autonegotiation/gig_ethernet_pcs_pma_sgmii_autonegotiation.xci
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_sgmii_autonegotiation/ip_0/synth/gig_ethernet_pcs_pma_sgmii_autonegotiation_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_sgmii_autonegotiation/ip_0/synth/gig_ethernet_pcs_pma_sgmii_autonegotiation_gt.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_sgmii_autonegotiation/gig_ethernet_pcs_pma_sgmii_autonegotiation_board.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_sgmii_autonegotiation/synth/gig_ethernet_pcs_pma_sgmii_autonegotiation.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_sgmii_autonegotiation/synth/gig_ethernet_pcs_pma_sgmii_autonegotiation_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_sgmii_autonegotiation/synth/gig_ethernet_pcs_pma_sgmii_autonegotiation_ooc.xdc]

read_ip -quiet /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gbe_cpu_buffer/gbe_cpu_buffer.xci
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gbe_cpu_buffer/gbe_cpu_buffer_ooc.xdc]

read_ip -quiet /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gbe_arp_cache/gbe_arp_cache.xci
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gbe_arp_cache/gbe_arp_cache_ooc.xdc]

read_ip -quiet /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gpio_pins3_c_counter_binary_v12_0_i1/gpio_pins3_c_counter_binary_v12_0_i1.xci
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gpio_pins3_c_counter_binary_v12_0_i1/gpio_pins3_c_counter_binary_v12_0_i1_ooc.xdc]

read_ip -quiet /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gpio_pins3_c_counter_binary_v12_0_i2/gpio_pins3_c_counter_binary_v12_0_i2.xci
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gpio_pins3_c_counter_binary_v12_0_i2/gpio_pins3_c_counter_binary_v12_0_i2_ooc.xdc]

read_ip -quiet /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gpio_pins3_c_counter_binary_v12_0_i0/gpio_pins3_c_counter_binary_v12_0_i0.xci
set_property used_in_implementation false [get_files -all /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gpio_pins3_c_counter_binary_v12_0_i0/gpio_pins3_c_counter_binary_v12_0_i0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/constrs_1/imports/gpio_pins3/user_const.xdc
set_property used_in_implementation false [get_files /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/constrs_1/imports/gpio_pins3/user_const.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xcku115-flvf1924-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
