# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_axi_timer_0_0/cont_microblaze_axi_timer_0_0.xci
# IP: The module: 'cont_microblaze_axi_timer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_axi_timer_0_0/cont_microblaze_axi_timer_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'cont_microblaze_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_axi_timer_0_0/cont_microblaze_axi_timer_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cont_microblaze_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_axi_timer_0_0/cont_microblaze_axi_timer_0_0.xci
# IP: The module: 'cont_microblaze_axi_timer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_axi_timer_0_0/cont_microblaze_axi_timer_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'cont_microblaze_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/bd/cont_microblaze/ip/cont_microblaze_axi_timer_0_0/cont_microblaze_axi_timer_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cont_microblaze_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
