# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_sgmii_autonegotiation/gig_ethernet_pcs_pma_sgmii_autonegotiation.xci
# IP: The module: 'gig_ethernet_pcs_pma_sgmii_autonegotiation' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_sgmii_autonegotiation/ip_0/gig_ethernet_pcs_pma_sgmii_autonegotiation_gt.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gig_ethernet_pcs_pma_sgmii_autonegotiation_gt || ORIG_REF_NAME==gig_ethernet_pcs_pma_sgmii_autonegotiation_gt} -quiet] -quiet

# XDC: /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_sgmii_autonegotiation/ip_0/synth/gig_ethernet_pcs_pma_sgmii_autonegotiation_gt_ooc.xdc

# XDC: /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_sgmii_autonegotiation/ip_0/synth/gig_ethernet_pcs_pma_sgmii_autonegotiation_gt.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gig_ethernet_pcs_pma_sgmii_autonegotiation_gt || ORIG_REF_NAME==gig_ethernet_pcs_pma_sgmii_autonegotiation_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_sgmii_autonegotiation/gig_ethernet_pcs_pma_sgmii_autonegotiation_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_sgmii_autonegotiation'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_sgmii_autonegotiation/synth/gig_ethernet_pcs_pma_sgmii_autonegotiation.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_sgmii_autonegotiation'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_sgmii_autonegotiation/synth/gig_ethernet_pcs_pma_sgmii_autonegotiation_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_sgmii_autonegotiation'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_sgmii_autonegotiation/synth/gig_ethernet_pcs_pma_sgmii_autonegotiation_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_sgmii_autonegotiation'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_sgmii_autonegotiation/gig_ethernet_pcs_pma_sgmii_autonegotiation.xci
# IP: The module: 'gig_ethernet_pcs_pma_sgmii_autonegotiation' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_sgmii_autonegotiation/ip_0/gig_ethernet_pcs_pma_sgmii_autonegotiation_gt.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gig_ethernet_pcs_pma_sgmii_autonegotiation_gt || ORIG_REF_NAME==gig_ethernet_pcs_pma_sgmii_autonegotiation_gt} -quiet] -quiet

# XDC: /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_sgmii_autonegotiation/ip_0/synth/gig_ethernet_pcs_pma_sgmii_autonegotiation_gt_ooc.xdc

# XDC: /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_sgmii_autonegotiation/ip_0/synth/gig_ethernet_pcs_pma_sgmii_autonegotiation_gt.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gig_ethernet_pcs_pma_sgmii_autonegotiation_gt || ORIG_REF_NAME==gig_ethernet_pcs_pma_sgmii_autonegotiation_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_sgmii_autonegotiation/gig_ethernet_pcs_pma_sgmii_autonegotiation_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_sgmii_autonegotiation'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_sgmii_autonegotiation/synth/gig_ethernet_pcs_pma_sgmii_autonegotiation.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_sgmii_autonegotiation'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_sgmii_autonegotiation/synth/gig_ethernet_pcs_pma_sgmii_autonegotiation_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_sgmii_autonegotiation'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gig_ethernet_pcs_pma_sgmii_autonegotiation/synth/gig_ethernet_pcs_pma_sgmii_autonegotiation_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_sgmii_autonegotiation'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
