# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gbe_tx_packet_fifo/gbe_tx_packet_fifo.xci
# IP: The module: 'gbe_tx_packet_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gbe_tx_packet_fifo/gbe_tx_packet_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'gbe_tx_packet_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gbe_tx_packet_fifo/gbe_tx_packet_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'gbe_tx_packet_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gbe_tx_packet_fifo/gbe_tx_packet_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gbe_tx_packet_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gbe_tx_packet_fifo/gbe_tx_packet_fifo.xci
# IP: The module: 'gbe_tx_packet_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gbe_tx_packet_fifo/gbe_tx_packet_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'gbe_tx_packet_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gbe_tx_packet_fifo/gbe_tx_packet_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'gbe_tx_packet_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/kplant/lwa_firmware/gpio_pins3/myproj/myproj.srcs/sources_1/ip/gbe_tx_packet_fifo/gbe_tx_packet_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gbe_tx_packet_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
